package com.aakash.lab;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.os.Bundle;
import android.view.MotionEvent;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.Toast;

import com.aakash.lab.SimpleGestureFilter.SimpleGestureListener;

public class ImagePlotActivity extends Activity implements
		SimpleGestureListener {
	private SimpleGestureFilter detector;

	// SimpleGesture for the swipe feature
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.main2);

		detector = new SimpleGestureFilter(this, this);
		// close button to return to two column web page
		Button btnOpenNewActivity = (Button) findViewById(R.id.button1);
		btnOpenNewActivity.setOnClickListener(new View.OnClickListener() {
			// switching to next activity
			public void onClick(View v) {
				Intent myIntent = new Intent();
				sci.clearFlag();
				finish();
			}
		});
		// image view to display the plot
		ImageView img = (ImageView) findViewById(R.id.imageView1);
		/* give path of actual image file generated by cgi script below */
		Bitmap bmp = BitmapFactory
				.decodeFile("/data/local/linux/var/www/html/scilab/tmp/1.gif");
		img.setImageBitmap(bmp);
	}

	public boolean dispatchTouchEvent(MotionEvent me) {
		this.detector.onTouchEvent(me);
		return super.dispatchTouchEvent(me);
	}

	// Swipe feature to cross check the output and graphical output, switch
	// between screen if image file exists
	public void onSwipe(int direction) {

		switch (direction) {

		case SimpleGestureFilter.SWIPE_RIGHT:
			finish();

			break;

		}

	}

	public void onDoubleTap() {

	}

}
